<?php

namespace MyProject\Services;

use MyProject\Models\Users\User;

class EmailSender{
	public static function send(
		User $receiver,
		string $subject,
		string $templateName,
		array $templateVars = []
	): void {
		extract($templateVars);
		
		ob_start();
		require __DIR__ . '/../../template/mail/' . $templateName; //эта разметка отправится письмом 
		$body = ob_get_contents();
		ob_end_clean();
		
		$transport = (new \Swift_SmtpTransport('smtp.mailtrap.io', 2525))
		->setUsername('') // generated by Mailtrap
		->setPassword('') // generated by Mailtrap
		;
		$mailer = new \Swift_Mailer($transport);
		
		$message = (new \Swift_Message())
		// Add subject
		->setSubject($subject)
		
		//Put the From address
		->setFrom(['admin@example.com'])
		
		// Include several To addresses
		->setTo(['dima@yandex.ru' => 'Подтверждение регистрации']);
		
		$message->setBody($body, 'text/html');
		
		$mailer->send($message);
	}
}
